name: api
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: podman build -f apps/api/Containerfile -t homeflow/api:${{ github.sha }} .
