name: db
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -f db/Dockerfile -t homeflow/db-migrate:${{ github.sha }} .
