name: web
on:
  push:
    branches: [main]
    paths:
      - apps/web/**
      - packages/ts-common/**
      - packages/contracts/**
      - .github/workflows/web.yml
  pull_request:
    paths:
      - apps/web/**
      - packages/ts-common/**
      - packages/contracts/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -f apps/web/Dockerfile -t homeflow/web:${{ github.sha }} .
